MYPAGE = "http://ultimate-a.cygames.jp/ultimate/mypage/index"
FUSION = "http://ultimate-a.cygames.jp/ultimate/card_union"
MISSION_2_3 = "http://ultimate-a.cygames.jp/ultimate/quest/play/2/3"
MISSION_2_4 = "http://ultimate-a.cygames.jp/ultimate/quest/play/2/4"
CARD_LIST_INDEX = "http://ultimate-a.cygames.jp/ultimate/card_list/index/0/1/0/"
CARD_LIST_DESC = "http://ultimate-a.cygames.jp/ultimate/card_list/desc/"
PACKS = "http://ultimate-a.cygames.jp/ultimate/gacha?viewer_id=null"
GET_RALLY_PACK = "http://ultimate-a.cygames.jp/ultimate/gacha/index/0?hash=free"